<?php
// Content records are independent of templates. Add verified evidence before publishing claims.
$services = [
 'web-development' => ['Web Development', 'A website built around what your business needs.', 'A slow, confusing website makes it harder for people to understand your business and take the next step.', 'We turn your content and workflows into a clear, responsive website with reusable sections and a manageable codebase.', ['Responsive website development','Design-to-code implementation','Accessible navigation and forms','Technical SEO foundations'], 'HTML · CSS · JavaScript · PHP', 'code'],
 'wordpress' => ['WordPress Development', 'A website your team can actually manage.', 'Updating a business website should not mean fighting its theme or relying on a developer for every sentence.', 'We build focused WordPress pages, editing patterns and integrations around your publishing workflow.', ['Custom page layouts','Theme customization','Content migration planning','Plugin setup and cleanup'], 'WordPress · PHP · JavaScript', 'layout'],
 'woocommerce' => ['WooCommerce Development', 'Connect your content and your store.', 'A store needs more than product pages: customers need a clear route through variations, shipping and checkout.', 'We organize your WooCommerce catalog and storefront around how your customers shop and your team operates.', ['Product and category structure','Storefront customization','Checkout configuration','Integration and launch checks'], 'WordPress · WooCommerce · PHP', 'shop'],
 'shopify' => ['Shopify Development', 'Make your storefront feel like your brand.', 'An off-the-shelf storefront can leave your products, offers and buying experience feeling disconnected.', 'We develop Shopify sections and storefront improvements that fit your content and customer journey.', ['Custom theme sections','Product page improvements','Responsive storefronts','App integration support'], 'Shopify · Liquid · JavaScript', 'shop'],
 'ecommerce' => ['E-Commerce Solutions', 'A practical plan for selling online.', 'Choosing a platform without understanding your catalog, payments and operations can create expensive rework.', 'We help map your store requirements, choose a suitable implementation and build the buying journey.', ['Platform and catalog planning','Product discovery and navigation','Payment and shipping setup','Store launch checklist'], 'Shopify · WooCommerce · APIs', 'shop'],
 'web-applications' => ['Web Applications', 'Tools that fit the way your business works.', 'Spreadsheets and disconnected tools become hard to manage when the same information is entered repeatedly.', 'We scope focused applications with clear user roles, useful interfaces and maintainable integrations.', ['Internal dashboards','Customer-facing portals','Data and workflow design','Responsive application interfaces'], 'JavaScript · .NET / ASP.NET Core · SQL Server · REST APIs', 'code'],
 'maintenance' => ['Website Maintenance', 'Keep your website ready for everyday use.', 'Small issues accumulate: outdated dependencies, broken forms and content changes all need attention.', 'We agree a maintenance scope that covers the systems and pages your business relies on.', ['Bug investigation','Content and layout updates','Dependency update planning','Backup and recovery checks'], 'WordPress · Shopify · Custom websites', 'tools'],
 'performance' => ['Performance Optimization', 'Less waiting. A smoother experience.', 'Heavy assets and unnecessary scripts can make even a well-designed website frustrating on a phone.', 'We measure key journeys, identify the largest bottlenecks and prioritize changes that can be verified.', ['Loading and rendering audit','Image and font optimization','Script and stylesheet cleanup','Before-and-after measurement'], 'Browser DevTools · Lighthouse · Core Web Vitals', 'bolt'],
 'hosting-deployment' => ['Hosting & Deployment', 'Take your project from local to live.', 'A working local project still needs a production environment, configuration, HTTPS and a recovery plan.', 'We help prepare your hosting environment and create a repeatable release checklist for your application.', ['Hosting environment setup','Environment configuration','HTTPS and launch checks','Deployment and rollback planning'], 'Linux · Git · Hosting · Cloud', 'launch'],
 'domains-dns' => ['Domain Configuration', 'Get your domain pointing the right way.', 'DNS changes can affect both your website and your email if existing records are not understood first.', 'We review the current records and plan the domain connection around the services you need to preserve.', ['Domain-to-host connection','DNS record review','Subdomain configuration','HTTPS verification'], 'Domains · DNS · SSL/TLS', 'globe'],
 'api-integrations' => ['API Integrations', 'Make your systems work together.', 'Manually moving information between tools takes time and creates opportunities for mistakes.', 'We design integrations around the data you need, with explicit handling for errors and credentials.', ['Third-party API connections','Webhook workflows','Form-to-system integrations','Error handling and documentation'], 'REST APIs · Webhooks · PHP · JavaScript', 'link'],
 'ai-integration' => ['AI Integration', 'Put AI to work on a specific problem.', 'A useful AI feature needs a defined task, suitable data and a way to check the output.', 'We scope small, testable AI workflows and build the human review and privacy requirements into the design.', ['Use-case discovery','API-based prototypes','Review and fallback workflows','Evaluation planning'], 'AI APIs · Business workflows · Evaluation', 'spark'],
 'automation' => ['Business Automation', 'Spend less time moving the same information.', 'Repetitive admin work often hides in handoffs between forms, inboxes and business tools.', 'We map a process before automating it, so exceptions, approvals and ownership remain clear.', ['Workflow mapping','Form and notification flows','System-to-system handoffs','Logging and exception handling'], 'APIs · Webhooks · Business tools', 'flow'],
];
$categories = ['web-development'=>'Web Development','wordpress'=>'WordPress','shopify'=>'Shopify','e-commerce'=>'E-Commerce','ai'=>'AI','devops'=>'DevOps','git-github'=>'Git & GitHub','hosting-deployment'=>'Hosting & Deployment'];
// Planned courses: do not invent duration, lesson counts, instructors, prices or reviews.
$courseRows = [
 ['html','HTML for Beginners','web-development','Beginner','Build the structure of your first website.',['Semantic page structure','Links, images and lists','Accessible forms'],'A personal introduction page'],
 ['css','CSS: From Basics to Responsive Websites','web-development','Beginner','Turn plain HTML into layouts that work on every screen.',['The cascade and box model','Flexbox and Grid','Responsive layouts'],'A responsive business landing page'],
 ['javascript','JavaScript Fundamentals','web-development','Beginner','Add useful interactions to your websites.',['Variables and functions','DOM events','Working with data'],'An interactive project directory'],
 ['front-end','Complete Front-End Development','web-development','Intermediate','Connect structure, styling and interaction in one project.',['Component thinking','Accessible interactions','Browser testing'],'A complete multi-page website'],
 ['wordpress-website','WordPress: Zero to Live Website','wordpress','Beginner','Plan, build and publish a content-driven website.',['Pages and content','Themes and plugins','Launch preparation'],'A small business website'],
 ['woocommerce-store','WooCommerce Store Development','e-commerce','Intermediate','Create the structure and buying flow for an online store.',['Product catalogs','Store configuration','Checkout testing'],'A practice WooCommerce store'],
 ['shopify-store','Shopify Store Development','shopify','Beginner','Build a storefront around products and customers.',['Store structure','Theme sections','Launch checks'],'A practice Shopify storefront'],
 ['git-github-basics','Git & GitHub for Beginners','git-github','Beginner','Track changes and collaborate with confidence.',['Commits and history','Branches','Pull requests'],'A version-controlled website repository'],
 ['domains-hosting','Domain & Hosting Fundamentals','hosting-deployment','Beginner','Understand how a website becomes reachable online.',['Domains and DNS','Hosting choices','HTTPS basics'],'A documented hosting and domain plan'],
 ['publish-a-website','How to Publish a Website','hosting-deployment','Beginner','Move a small website from your computer to the web.',['Production files','Domain connection','Post-launch checks'],'A published practice website'],
 ['website-deployment','Website Deployment Fundamentals','hosting-deployment','Intermediate','Build a repeatable route to production.',['Environment settings','Release workflows','Rollback planning'],'A deployment runbook'],
 ['devops-basics','DevOps for Beginners','devops','Beginner','Connect development, delivery and operations.',['Version control workflows','CI/CD concepts','Monitoring and backups'],'A delivery pipeline plan'],
 ['linux','Linux Basics for Developers','devops','Beginner','Get comfortable with the environment behind many servers.',['Files and permissions','Processes and services','Safe command-line habits'],'A local Linux practice environment'],
 ['docker','Docker Fundamentals','devops','Intermediate','Learn how containers package an application environment.',['Images and containers','Volumes and networking','Environment configuration'],'A containerized practice application'],
 ['ai-basics','AI for Beginners','ai','Beginner','Understand where AI can help and where to check its work.',['AI capabilities and limits','Clear instructions','Output verification'],'A documented AI-assisted task'],
 ['chatgpt-work','ChatGPT for Work & Business','ai','Beginner','Explore practical drafting and planning workflows.',['Task context','Reviewing drafts','Handling sensitive information'],'A reusable work-assistance workflow'],
 ['ai-developers','AI for Developers','ai','Intermediate','Use AI throughout a development task, with review.',['Code explanation','Debugging and testing','Reviewing generated changes'],'An AI-assisted feature with tests'],
 ['prompt-engineering','Prompt Engineering','ai','Beginner','Write instructions you can evaluate and improve.',['Context and constraints','Examples and output formats','Comparing results'],'A small prompt evaluation notebook'],
 ['ai-ecommerce','AI for E-Commerce','ai','Beginner','Explore practical assistance for store operations.',['Product content drafts','Catalog checks','Human review'],'A reviewed product content workflow'],
 ['ai-automation','AI Automation Fundamentals','ai','Intermediate','Design workflows with clear boundaries and human checks.',['Inputs and outputs','API workflow concepts','Approvals and fallbacks'],'An automation prototype plan'],
];
$courses = [];
foreach ($courseRows as [$slug,$title,$category,$level,$description,$curriculum,$project]) {
 $courses[$slug] = compact('slug','title','category','level','description','curriculum','project') + ['status'=>'planned','duration'=>null,'lessons'=>null,'price'=>null,'instructor'=>null,'reviews'=>[]];
}
$courses['html']['sample'] = 'courses/html/first-page';
$projectCategories = ['shopify'=>'Shopify', 'figma-shopify'=>'Figma to Shopify', 'wordpress'=>'WordPress', 'other'=>'Wix & Squarespace'];
$projects = array_values(array_filter(
 json_decode(file_get_contents(__DIR__.'/data/projects.json'), true, 512, JSON_THROW_ON_ERROR),
 fn(array $project): bool => $project['published'] === true
));
$resources = [
 'domain-hosting'=>['Domains, DNS & hosting: what goes where?','A plain-language guide to the parts that make a website reachable.','LAUNCH NOTES',[
  ['A domain is the address','Your domain is the name people use to reach a site. Registration gives you control of that name for the registration period; it does not automatically provide a website or mailbox.'],
  ['Hosting runs or serves the website','Hosting provides the environment for your files and application. A static website and a PHP application have different requirements. List your runtime, database and storage needs before selecting an environment.'],
  ['DNS connects the pieces','DNS records direct traffic to the appropriate services. Website and email records serve different purposes. Record the current configuration before making changes, especially when a domain already receives email.'],
  ['Prepare the launch','Confirm the destination host, preserve existing email records, connect the domain, enable HTTPS and check the main pages and forms. Keep the previous configuration so you have a route back if something fails.']]],
 'git-github'=>['Git and GitHub: a practical starting point','Understand the difference between local version history and a shared repository.','DEVELOPER NOTES',[
  ['Start with version history','Git records snapshots of changes in a repository. A commit should represent a coherent change with a message that explains its purpose. Review what is staged before you commit.'],
  ['Keep private configuration private','Do not commit passwords, API keys or environment files. Use an ignore file for local configuration and document the variable names separately without real values. If a secret has been committed, removing the file alone does not erase its history.'],
  ['Use a branch for a focused change','A branch lets you work on a change independently. Make small commits, check the result and review the difference before merging. GitHub can host the repository and provide pull requests for that review.'],
  ['A repository is not a deployment','Uploading code does not automatically put your website online. Deployment is a separate step that moves the intended version into the right running environment. Document how those steps connect.']]],
 'deployment'=>['Before you launch: a website checklist','A focused checklist for moving from a working local site to a working public site.','LAUNCH NOTES',[
  ['Check the production environment','Confirm the runtime version, required extensions, writable directories and environment variables. Keep credentials outside the public response and disable detailed error output for visitors.'],
  ['Check the visitor journey','Open the website on a narrow screen. Follow navigation links, submit a controlled form test and check the confirmation. Test keyboard navigation, readable text and a useful not-found page.'],
  ['Check search and sharing','Review page titles, descriptions, canonical URLs and the social preview. Ensure the public site can be indexed while staging remains excluded. Check the sitemap and avoid redirecting missing pages indiscriminately to the homepage.'],
  ['Prepare a recovery path','Back up the current files and data, record the release steps and decide how to roll back. After launch, check errors, forms and key pages again. A backup is more useful when you know how to restore it.']]],
 'ai'=>['A review-first workflow for AI-assisted work','Make the task specific, protect your inputs and check the output.','AI FIELD NOTES',[
  ['Define the task before the prompt','Write down the result you need and what would make it acceptable. A clear task such as drafting a product description from approved specifications is easier to evaluate than a request to improve everything.'],
  ['Share only appropriate context','Remove passwords, personal information and confidential business data from examples. Use sample data where possible and understand your chosen tool’s data handling before sharing business information.'],
  ['Treat the output as a draft','Check factual claims against reliable source material. Run and review generated code in an appropriate test environment. Look for invented details, missing edge cases and assumptions that were never agreed.'],
  ['Keep a person responsible','For actions that send messages, publish content or change systems, define a review step. Record what worked, what failed and what needs a fallback before expanding the workflow.']]],
];
$pages = [
 ''=>['Build. Learn. Launch. | Webostics','Web development, e-commerce, practical technology learning, AI and deployment. Build with Webostics or explore your next learning path.','home'],
 'services'=>['Web Development & E-Commerce Services | Webostics','Explore website, Shopify, WordPress, application, automation and deployment services. Tell Webostics what you need to build.','services'],
 'courses'=>['Practical Technology Learning Paths | Webostics','Explore planned courses in web development, WordPress, Shopify, AI and DevOps. See course outlines and ask about availability.','courses'],
 'ai'=>['Practical AI Learning & Integration | Webostics','Explore practical AI use cases for developers, students and businesses, with verification, privacy and human review built in.','ai'],
 'devops'=>['Deployment & DevOps Learning | Webostics','Understand the journey from local code to production: Git, domains, hosting, environments, CI/CD, monitoring and backups.','devops'],
 'projects'=>['Website & E-Commerce Portfolio | Saad Ahmad at Webostics','Explore Saad Ahmad’s Shopify, WordPress, Wix and Squarespace portfolio, including storefronts, custom themes and business websites.','projects'],
 'resources'=>['Web Development & Launch Resources | Webostics','Practical guides to domains, hosting, Git, deployment and responsible AI-assisted work. Build a clearer route from learning to launch.','resources'],
 'about'=>['About Webostics | Build. Learn. Launch.','Webostics brings website development, e-commerce, practical technology learning and deployment together in one place.','about'],
 'contact'=>['Contact Webostics | Projects & Course Inquiries','Discuss a website project, ask about a planned course or send a general inquiry. Contact Webostics directly.','contact'],
 'privacy'=>['Privacy & Contact Inquiries | Webostics','How Webostics handles information submitted through contact forms, inquiry emails and spam protection.','privacy'],
];
foreach ($services as $slug=>$s) $pages['services/'.$slug]=[$s[0].' | Webostics',$s[1].' '.$s[3],'service'];
foreach ($categories as $slug=>$name) $pages['courses/'.$slug]=[$name.' Learning Path | Webostics','Explore the planned '.$name.' learning path, practical project ideas and course outlines at Webostics.','category'];
foreach ($courses as $slug=>$c) $pages['courses/'.$slug]=[$c['title'].' | Webostics',$c['description'].' View the planned outline and inquire about availability.','course'];
foreach ($resources as $slug=>$r) $pages['resources/'.$slug]=[$r[0].' | Webostics',$r[1],'resource'];
$pages['courses/html/first-page'] = ['Build Your First HTML Page: Free Practice Lesson | Webostics','Learn HTML document structure, edit a starter page in a sandboxed preview, and download your own introduction page. Free practice with no account required.','lesson'];
