<?php
// Owner-supplied starting prices. Quantities and final scope are confirmed in a quote.
$pricingGroups = [
 'shopify'=>['title'=>'Shopify development','intro'=>'From an existing theme to a more tailored storefront. Bring your content, product information and design references.','times'=>['2','4–5','7–10'], 'summaries'=>['An existing-theme setup with supplied content and a design that fits the agreed theme scope.','A customized storefront with additional sections, UI work and selected integrations.','More involved storefront work with custom functionality and integrations.'], 'features'=>[
 ['Homepage, header & footer','Included','Included','Included'],['Collection & product page templates','Included','Included','Included'],['Cart / cart drawer','Included','Included','Included'],['Mobile responsive','Included','Included','Included'],['Custom sections','Not included','Included','Included'],['Advanced UI / animations','Not included','Included','Included'],['Third-party app integration','Not included','Basic','Advanced'],['Custom functionality','Not included','Limited','Included'],['Performance optimization','Basic','Included','Advanced'],['Testing & bug fixes','Included','Included','Included']]],
 'wordpress'=>['title'=>'WordPress / WooCommerce','intro'=>'Business websites, content-led sites and online stores, scoped around the pages and features you need.','times'=>['2–3','4–6','7–12'], 'summaries'=>['A simple business, portfolio or service website with supplied content.','A more customized website with Elementor design, a blog and selected integrations.','A WooCommerce store or advanced WordPress project with custom functionality.'], 'features'=>[
 ['Homepage, header & footer','Included','Included','Included'],['Responsive design','Included','Included','Included'],['Basic pages & contact form','Included','Included','Included'],['Custom Elementor design','Not included','Included','Included'],['Blog setup','Not included','Included','Included'],['WooCommerce','Not included','Optional · quoted separately','Included'],['Product / collection pages','Not included','Optional · quoted separately','Included'],['Cart & checkout','Not included','Optional · quoted separately','Included'],['Payment gateway','Not included','Optional · quoted separately','Included'],['Custom functionality','Not included','Limited','Included'],['Speed optimization','Basic','Included','Advanced'],['Testing & bug fixes','Included','Included','Included']]],
];
$pricingPlans=[];
foreach ($pricingGroups as $platform=>$group) {
 foreach (['basic','standard','premium'] as $i=>$tier) {
  $pricingPlans[$platform.'-'.$tier]=['name'=>ucfirst($tier),'platform'=>$platform,'topic'=>$platform==='wordpress' && $tier==='premium' ? 'woocommerce' : $platform,'price'=>[15000,30000,60000][$i],'timeline'=>$group['times'][$i],'summary'=>$group['summaries'][$i],'index'=>$i];
 }
}
$pricingAddons=[['Additional page','2,000'],['Custom section / component','2,000'],['Payment gateway integration','5,000'],['Third-party app / plugin integration','3,000'],['Custom functionality','5,000'],['Advanced product / variant setup','3,000'],['Speed optimization','5,000'],['Basic SEO setup','5,000'],['Additional revision round','2,000'],['Monthly maintenance','5,000 / month']];
