<?php pageHero('BUILD · LEARN · LAUNCH', 'Meet the developer behind the work.', 'Webostics brings practical development and learning together: websites, storefronts and applications built with attention to how people use them.'); ?>
<div class="container page-content about-page">
<section class="developer-profile" id="saad-ahmad" aria-labelledby="developer-name">
  <figure class="developer-photo"><img src="<?= e(url('assets/team/saad-ahmad.png')) ?>" width="512" height="512" alt="Saad Ahmad" decoding="async"><figcaption>SAAD AHMAD / WEBOSTICS</figcaption></figure>
  <div class="developer-intro"><span class="eyebrow">YOUR DEVELOPER AT WEBOSTICS</span><h2 id="developer-name">Saad Ahmad</h2><p class="developer-role">Full-stack web, e-commerce & mobile app developer</p><p>I build Shopify storefronts, WordPress websites and Android applications. My strongest foundations are HTML, CSS, JavaScript—particularly jQuery—PHP and Shopify Liquid.</p><p>From a Figma design to a working storefront, I focus on responsive layouts, clear interactions and reusable code. My mobile work includes School Van Tracking, built with React Native, a Laravel backend and Next.js.</p><div class="button-row"><?php button('Discuss your project','contact?type=service'); button('View my work','projects','outline'); ?></div><a class="standalone-link" href="<?= e($linkedin) ?>" target="_blank" rel="noopener noreferrer">Connect on LinkedIn <span aria-hidden="true">&#8599;</span><span class="profile-link-note"> (opens in a new tab)</span></a></div>
</section>
<section class="about-section" aria-labelledby="expertise-heading"><div class="section-heading"><span class="eyebrow">HANDS-ON DEVELOPMENT</span><h2 id="expertise-heading">What I bring to your project.</h2></div><div class="expertise-grid">
<article><span class="icon-box"><?= icon('bag') ?></span><h3>Shopify & e-commerce</h3><p>Liquid, JSON templates, sections and blocks, theme settings, metafields, product and collection pages, and AJAX cart interactions.</p><a class="text-link" href="<?= e(url('services/shopify')) ?>">Shopify development &#8599;</a></article>
<article><span class="icon-box"><?= icon('code') ?></span><h3>Websites & front-end</h3><p>Figma-to-website implementation, HTML, CSS and JavaScript/jQuery, plus WordPress and WooCommerce layouts, custom styling, forms and plugin integrations.</p><a class="text-link" href="<?= e(url('services/web-development')) ?>">Website development &#8599;</a></article>
<article><span class="icon-box"><?= icon('mobile') ?></span><h3>Mobile applications</h3><p>Android app development with React Native, supported by Laravel backend work and Next.js within the application stack.</p><a class="text-link" href="<?= e(url('services/mobile-app-development')) ?>">Mobile development &#8599;</a></article>
</div></section>
<section class="about-section" aria-labelledby="profile-work"><div class="section-heading"><span class="eyebrow">EXPLORE THE WORK</span><h2 id="profile-work">From storefronts to mobile apps.</h2><p>Browse the current projects here on Webostics, with each project attributed to Saad Ahmad.</p></div><div class="profile-projects"><article><span class="eyebrow">SHOPIFY / LIQUID</span><h3>Co-Museum</h3><p>Full website development, translating a Figma design into a Shopify storefront with reusable sections and responsive layouts.</p><a class="text-link" href="<?= e(url('projects/co-museum')) ?>">Explore the project &#8599;</a></article><article><span class="eyebrow">ANDROID / REACT NATIVE</span><h3>School Van Tracking</h3><p>A published Android app for school-van location tracking and pickup/drop-off notifications, using React Native, Laravel and Next.js.</p><a class="text-link" href="<?= e(url('projects?platform=mobile#project-school-van-tracking')) ?>">View the mobile project &#8599;</a></article></div></section>
<section class="about-section content-grid"><div class="prose"><h2>A practical way of working.</h2><p>We start with your site, design or idea and agree the requirements. I build reusable sections or editable pages, test the important journeys on mobile and desktop, then explain the changes at handover.</p><ul><li>Start with the problem and the people using the result.</li><li>Choose tools that fit the scope and can be maintained.</li><li>Review the work in clear, manageable steps.</li><li>Plan testing, handover and deployment early.</li></ul></div><aside class="sidebar"><span class="eyebrow">LEARN WITH WEBOSTICS</span><h2>Build your own starting point.</h2><p>For students and new developers, Webostics offers free HTML practice lessons and practical resource guides. The wider course library is still in development.</p><?php button('Try a free HTML lesson','courses/html/first-page'); ?><p class="side-note">Course availability, instructors and schedules will be announced when confirmed.</p></aside></section>
</div>
<?php cta(); ?>
