<?php
$libraryRepo = 'https://github.com/SaadiDK-003/developers-library';
$libraryTopics = [
 ['foundations', '01', 'HTML, CSS & JavaScript', 'Start with page structure, responsive layouts and browser interactions. These notes collect learning links and references you can return to while building.', 'Build a responsive profile page. Add a button that reveals a short biography, and check that it works with a keyboard.', ['HTML'=>'html.md','CSS'=>'css.md','JavaScript'=>'javascript.md'], 'MDN web development curriculum', 'https://developer.mozilla.org/en-US/docs/Learn_web_development'],
 ['jquery', '02', 'jQuery & everyday interactions', 'Explore the repository’s dialog example as a code-reading exercise. Compare the jQuery approach with native browser APIs and check the example before reusing it.', 'Create an accessible dialog on a local page. Test opening, closing with Escape and returning focus to the opening button.', ['jQuery'=>'jquery.md'], 'jQuery API documentation', 'https://api.jquery.com/'],
 ['react-typescript', '03', 'React & TypeScript', 'Find links to component-based UI learning and TypeScript references. Use current documentation alongside the collected links, especially when setting up a new project.', 'Build a small filterable project list. Define a TypeScript type for each project and show a useful message when no projects match.', ['React'=>'React.md','TypeScript'=>'typescript.md'], 'React Learn', 'https://react.dev/learn'],
 ['backend', '04', 'PHP & Laravel', 'The backend notes include PHP environment commands and Laravel migration examples. Treat these as context-specific references, with your installed version and database in mind.', 'In a disposable local Laravel project, create a tasks table and a form that validates a task title. Show a readable error when the title is empty.', ['PHP'=>'php.md','Laravel'=>'laravel.md'], 'Laravel migration documentation', 'https://laravel.com/docs/migrations'],
 ['commerce', '05', 'Magento & WordPress tooling', 'Explore Magento setup notes and WordPress command-line references. Platform requirements and installation commands change, so check the current requirements before using older examples.', 'On a local test store, document the runtime and platform versions, then write a backup and deployment checklist. Keep real credentials out of your notes.', ['Magento'=>'magento.md','WP-CLI'=>'wp_cli/wordpress-cli.md'], 'Adobe Commerce developer documentation', 'https://developer.adobe.com/commerce/docs/'],
 ['git', '06', 'Git & a repeatable workflow', 'Use Git to track local changes and GitHub to share and review them. The repository’s workflow notes sit alongside our beginner guide to version history and deployment.', 'Create a practice repository, ignore local configuration, make a focused branch and review your changes before committing.', ['Git'=>'git.md'], 'Webostics Git & GitHub guide', url('resources/git-github')],
];
pageHero('THE DEVELOPER LIBRARY', 'Read a little. Build something.', 'A curated route through developer notes, useful references and small practice tasks. Free to explore, with no account required.');
?>
<div class="container page-content library-page">
<section class="library-intro" aria-labelledby="library-start"><div><span class="eyebrow">A WORKING REFERENCE COLLECTION</span><h2 id="library-start">Keep useful knowledge close.</h2><p>This collection draws on the Developers Library repository shared by Saad Ahmad, whose README credits SaadiDK and TahaAhmed123618. It brings together front-end and backend links, snippets and setup notes.</p><p>These are reference notes, not a complete course. The practice tasks below are starting points from Webostics to help you apply what you read.</p><a class="text-link" href="<?= e($libraryRepo) ?>">Browse the source on GitHub <span aria-hidden="true">&#8599;</span></a></div><aside class="sidebar"><span class="eyebrow">NEW TO BUILDING WEBSITES?</span><h2>Start with one page.</h2><p>Try our guided HTML lesson, edit a page in your browser and download your work. Then use this library when you need a reference.</p><?php button('Try the free HTML lesson', 'courses/html/first-page'); ?></aside></section>
<nav class="library-topics" aria-label="Developer library topics"><?php foreach ($libraryTopics as $topic): ?><a href="#<?= e($topic[0]) ?>"><?= e($topic[2]) ?></a><?php endforeach ?></nav>
<div class="library-grid"><?php foreach ($libraryTopics as [$id,$number,$title,$description,$practice,$notes,$docsTitle,$docsUrl]): ?>
<article class="library-card" id="<?= e($id) ?>" aria-labelledby="<?= e($id) ?>-heading"><span class="eyebrow">REFERENCE / <?= e($number) ?></span><h2 id="<?= e($id) ?>-heading"><?= e($title) ?></h2><p><?= e($description) ?></p><div class="library-practice"><h3>Make it practical</h3><p><?= e($practice) ?></p></div><div class="library-links"><h3>Explore the references</h3><ul><?php foreach ($notes as $label=>$file): ?><li><a href="<?= e($libraryRepo.'/blob/master/'.$file) ?>"><?= e($label) ?> notes on GitHub <span aria-hidden="true">&#8599;</span></a></li><?php endforeach ?><li><a href="<?= e($docsUrl) ?>"><?= e($docsTitle) ?> <span aria-hidden="true">&#8599;</span></a></li><?php if ($id === 'react-typescript'): ?><li><a href="https://www.typescriptlang.org/docs/handbook/intro.html">TypeScript Handbook <span aria-hidden="true">&#8599;</span></a></li><?php elseif ($id === 'commerce'): ?><li><a href="https://make.wordpress.org/cli/handbook/">WP-CLI Handbook <span aria-hidden="true">&#8599;</span></a></li><?php endif ?></ul></div></article>
<?php endforeach ?></div>
<section class="library-note" aria-labelledby="reference-context"><h2 id="reference-context">Use the notes with context.</h2><p>Some repository examples use older software versions. Setup, database-reset and permission commands can change your environment or remove data. Review the command, check current documentation and use a disposable local project before trying them.</p><p>Found a useful correction or reference? Visit the <a href="<?= e($libraryRepo) ?>">original repository</a> to suggest an improvement and help the shared collection grow.</p></section>
</div>
<?php cta(); ?>
