<?php
$starter = file_get_contents(dirname(__DIR__, 2).'/assets/learning/first-page.html');
pageHero('FREE PRACTICE LESSON / HTML FOR BEGINNERS', 'Your first page starts here.', 'Write a small introduction page, understand what each part does, and open your work in a browser. No account or payment needed.');
?>
<article class="container page-content lesson-layout">
  <nav class="lesson-toc" aria-label="Lesson sections"><strong>In this lesson</strong><a href="#understand">1. Understand the structure</a><a href="#try-it">2. Try the starter</a><a href="#practice">3. Make it your own</a><a href="#review">4. Check your understanding</a><a href="#next">5. Take the next step</a></nav>
  <div class="lesson-content">
    <div class="inline-banner"><p>This free practice lesson is available now. The complete HTML course is still being prepared; this lesson does not require enrollment or provide a certificate.</p></div>
    <section id="understand" class="prose"><h2>Give your content a structure.</h2><p>HTML describes the meaning and structure of a web page. An element usually has an opening tag, some content, and a closing tag. For example, <code>&lt;p&gt;Hello, world.&lt;/p&gt;</code> creates a paragraph. The browser interprets the tags and displays the content.</p><p>Start with the message you want someone to read. We’ll build a page with a heading, a short introduction, and a list of things you want to create.</p><h3>The document, from top to bottom</h3><dl class="lesson-definitions"><dt><code>&lt;!doctype html&gt;</code></dt><dd>Tells the browser to use modern HTML rendering rules. It is a declaration, not a visible element.</dd><dt><code>&lt;html lang="en"&gt;</code></dt><dd>The root element wraps the document. The language attribute identifies the content language for tools such as screen readers.</dd><dt><code>&lt;head&gt;</code></dt><dd>Contains document information: character encoding, the browser-tab title, and viewport settings. It does not hold the main visible content.</dd><dt><code>&lt;body&gt;</code></dt><dd>Contains the page’s visible content. In this example, a header introduces the page, main holds its central content, and a footer closes it.</dd></dl><h3>Choose tags for their meaning.</h3><p>Use <code>h1</code> for this page’s main heading and <code>h2</code> for its sections. A paragraph belongs in <code>p</code>. An unordered list uses <code>ul</code>, with each item inside an <code>li</code>. Heading levels describe the content hierarchy; choose them for that hierarchy rather than their default size.</p></section>
    <section id="try-it"><div class="section-heading"><span class="eyebrow">READ → CHANGE → PREVIEW</span><h2>Try the starter.</h2><p>Change the words between the tags, then update the preview. Notice what changes and what stays the same.</p></div><div class="lesson-playground" data-playground hidden><div class="editor-label-row"><label for="html-editor">Your HTML</label><span>Practice in your browser</span></div><textarea id="html-editor" spellcheck="false" autocapitalize="off" autocomplete="off" aria-describedby="editor-help"><?= e($starter) ?></textarea><p id="editor-help" class="form-help">Your edits stay on this page and are lost if you refresh. Download your HTML to keep it. The preview runs without scripts, forms, or external downloads.</p><div class="button-row"><button type="button" class="button primary" data-run>Update preview ↗</button><button type="button" class="button outline" data-download>Download my HTML ↓</button></div><p class="lesson-status" data-preview-status role="status"></p><div class="preview-label">Your page preview</div><iframe title="Preview of your practice HTML" sandbox="" referrerpolicy="no-referrer" data-preview></iframe></div><details class="lesson-source" open><summary>Read the starter HTML</summary><pre><code><?= e($starter) ?></code></pre></details><a class="text-link" href="<?= e(url('assets/learning/first-page.html')) ?>" download="index.html">Download the original starter ↓</a><p class="form-help">Without JavaScript, download the starter, open it in a text editor, make your changes, and reopen the saved file in your browser.</p></section>
    <section id="practice" class="prose"><h2>Make it your own.</h2><ol><li>Replace the main heading with your name or a short introduction.</li><li>Write two sentences about why you want to learn web development.</li><li>Change the list to three things you would like to build.</li><li>Add a new section titled “My next step” with an <code>h2</code> and a paragraph.</li><li>Change the text inside <code>title</code>. Download the file and open it in a browser tab to see where that title appears.</li></ol><h3>Save and open your page</h3><p>Save the file as <code>index.html</code>, using a plain-text editor and UTF-8 encoding. If your editor asks for a file type, choose all files so it does not append <code>.txt</code>. Open the file with your browser. This local file is on your computer; it is not yet a public website.</p><h3>If something looks wrong</h3><ul><li>If the browser shows your tags as text, check that the filename ends in <code>.html</code> and that you did not save a rich-text document.</li><li>If sections appear in an unexpected place, check closing tags and nesting. Close a child element before its parent.</li><li>If a change does not appear, save the file and refresh the browser. In the practice editor, choose “Update preview.”</li></ul></section>
    <section id="review" class="prose"><h2>Can you explain your page?</h2><p>Try answering before opening each explanation. These are self-check questions, not a graded test.</p><?php faq([['Where does the page title belong?','Inside the title element within head. It labels the browser tab. The visible main heading is a separate h1 element inside body.'],['How do you add another list item?','Add another li element inside the existing ul, keeping its opening and closing tags together.'],['Why use main, header and footer?','They describe the roles of parts of the page. This makes the structure easier for people, assistive tools and future developers to understand.'],['Is your downloaded file already online?','No. Opening a local HTML file displays it on your computer. Publishing it requires putting the file on a suitable host and making it reachable.']]); ?><h3>Your finished-page checklist</h3><ul><li>The browser tab has a meaningful title.</li><li>The page has one clear main heading and logically ordered sections.</li><li>Each list item is inside the list.</li><li>The file opens correctly after you save and reopen it.</li><li>You can explain the difference between head and body.</li></ul></section>
    <section id="next" class="inline-banner"><h2>Keep the page. Build on it.</h2><p>Next, explore links, images and accessible forms. CSS can then control the layout and presentation of the structure you’ve created.</p><div class="related-links"><a href="<?= e(url('courses/html')) ?>">View the planned HTML course ↗</a><a href="<?= e(url('courses/css')) ?>">Explore the CSS outline ↗</a><a href="<?= e(url('resources/domain-hosting')) ?>">Understand domains and hosting ↗</a></div></section>
  </div>
</article>
<script src="<?= e(asset('js/lesson.js')) ?>" defer></script>
