<?php pageHero('FREE PRACTICE LESSON / HTML FOR BEGINNERS', 'Connect your pages. Guide your reader.', 'Build a small two-page project. Learn how links, file paths and page sections fit together, then check your navigation with a keyboard.'); ?>
<article class="container page-content lesson-layout">
<nav class="lesson-toc" aria-label="Lesson sections"><strong>In this lesson</strong><a href="#understand">1. Understand a link</a><a href="#paths">2. Choose the right path</a><a href="#practice">3. Build two connected pages</a><a href="#review">4. Test the navigation</a><a href="#next">5. Take the next step</a></nav>
<div class="lesson-content">
<div class="inline-banner"><p>This is a free standalone practice lesson. Start with <a class="text-link" href="<?= e(url('courses/html/first-page')) ?>">your first HTML page</a> if tags and document structure are new to you. The complete course remains planned.</p></div>
<section id="understand" class="prose"><h2>A link has a destination and a label.</h2><p>An anchor element, <code>a</code>, connects one location to another. Its <code>href</code> attribute holds the destination; the text between its tags tells the reader what they will find.</p><pre class="lesson-code"><code>&lt;a href="about.html"&gt;About this notebook&lt;/a&gt;</code></pre><p>Here, the browser looks for a file named <code>about.html</code> relative to the current document. The visible label is “About this notebook.” A clear label is more useful than repeated “click here” links, especially when someone scans a page or navigates using assistive technology.</p><h3>Links and buttons have different jobs.</h3><p>Use a link to go somewhere: another page, a document, or a section of the current page. Use a button for an action such as submitting a form or opening an interactive menu. A button-shaped design does not change that underlying purpose.</p></section>
<section id="paths" class="prose"><h2>Three destinations to understand.</h2><dl class="lesson-definitions"><dt><code>href="about.html"</code></dt><dd>A relative path: look beside the current document for about.html. Moving both files together keeps this connection intact.</dd><dt><code>href="https://webostics.com/resources"</code></dt><dd>An absolute web address: open that resource page on the Webostics website. You need an internet connection to visit it.</dd><dt><code>href="#projects"</code></dt><dd>A fragment: navigate to the element whose id is projects in the current document. The spelling must match the id.</dd></dl><h3>Give a section an address.</h3><pre class="lesson-code"><code>&lt;a href="#projects"&gt;My projects&lt;/a&gt;

&lt;section id="projects"&gt;
  &lt;h2&gt;My projects&lt;/h2&gt;
  &lt;p&gt;A few things I want to build.&lt;/p&gt;
&lt;/section&gt;</code></pre><p>Each id should identify one element within the page. A fragment may not visibly scroll if the target is already on screen or the document is too short; check that the address ends with <code>#projects</code> as well.</p><h3>Watch the starting slash.</h3><p><code>about.html</code> is relative to the current directory. On a hosted website, <code>/about.html</code> starts at the domain root. Those are different locations when your site lives in a subdirectory. Keep the relative paths in this local exercise.</p></section>
<section id="practice"><div class="section-heading"><span class="eyebrow">TWO FILES. A WORKING CONNECTION.</span><h2>Build your project notebook.</h2><p>Download both files into the same folder. Keep their names unchanged for the first test.</p></div><div class="button-row"><a class="button primary" href="<?= e(url('assets/learning/links-and-navigation.html')) ?>" download="links-and-navigation.html">Download notebook ↓</a><a class="button outline" href="<?= e(url('assets/learning/about.html')) ?>" download="about.html">Download about page ↓</a></div><p class="form-help">The files open locally without an account or server. Only the external resource link needs internet access.</p><details class="lesson-source"><summary>Read the notebook starter</summary><pre><code><?= e(file_get_contents(dirname(__DIR__, 2).'/assets/learning/links-and-navigation.html')) ?></code></pre></details><div class="prose"><ol><li>Open <code>links-and-navigation.html</code> in a browser and follow “About this notebook.”</li><li>Use “Return to my project notebook” on the second page. Confirm that you return to the first file.</li><li>Follow “My projects.” Check the <code>#projects</code> fragment in the address bar.</li><li>Change the project ideas and the about-page text using a plain-text editor.</li><li>Add a section with <code>id="next-step"</code> and an <code>h2</code>. Add a navigation link to <code>#next-step</code>.</li><li>Rename <code>about.html</code> to <code>my-story.html</code>, update the corresponding link, and test both directions again.</li></ol><h3>Give navigation a clear structure.</h3><p>The starter places its main navigation inside <code>nav</code> and uses a list for related links. The <code>aria-label</code> names this navigation region. Your ordinary text links still work without JavaScript or a custom menu.</p></div></section>
<section id="review" class="prose"><h2>Test what a reader will do.</h2><ul><li>Press Tab to move through the links. Keep the browser’s visible focus indicator.</li><li>Press Enter on a focused link and confirm its destination.</li><li>Check that every navigation label describes the page or section it opens.</li><li>Test from both pages, not only from the first one.</li><li>If a local link fails, compare the folder, filename and capitalization with its href. Check that your editor has not added .txt.</li></ul><?php faq([['Why does about.html work when both files are in one folder?','The browser resolves this relative path against the current document location. It looks in the same folder because the path contains only a filename.'],['Why might a fragment link appear to do nothing?','Its target might already be visible. Also check that the target id exists, is unique, and matches the fragment spelling.'],['Should every external link open a new tab?','Opening in the same tab is a predictable default. If you intentionally choose a new tab, make that behavior clear to the visitor.'],['Why can a link work locally but fail after upload?','The uploaded directory structure or filename capitalization may differ. Check the actual hosted path and test each link again after deployment.']]); ?></section>
<section id="next" class="inline-banner"><h2>A small website you can navigate.</h2><p>You now have two connected pages and a section link. Keep these files: they give you something real to style when you start CSS.</p><div class="related-links"><a href="<?= e(url('courses/html/first-page')) ?>">Review the first HTML lesson ↗</a><a href="<?= e(url('courses/html')) ?>">See the planned HTML course ↗</a><a href="<?= e(url('courses/css')) ?>">Explore the CSS outline ↗</a></div></section>
</div></article>
