<?php if ($page[2] === 'lesson'): require __DIR__.'/lesson.php'; ?>
<?php elseif ($page[2] === 'services'): ?>
<?php pageHero('BUILD WITH WEBOSTICS','Built for the way you work.','A business website, a better storefront, or an application that saves your team time. Start with the problem. We’ll help you plan the build.'); ?>
<section class="container page-content"><div class="service-grid"><?php foreach ($services as $key=>$service) serviceCard($key,$service); ?></div><div class="compact-split"><div><?php sectionTitle('A CLEAR WAY FORWARD','From brief to working product.'); ?><p>Define the scope, build in reviewable steps, test the important journeys, and prepare the handover.</p></div><div><?php faq([['Not sure which service you need?','Share your current website, what is getting in the way, and what you want to achieve. We can start with the requirements before choosing a platform.'],['How are projects priced?','Pricing depends on the agreed scope, integrations, content and timeline. Send a project brief to discuss an estimate; there is no one-size-fits-all package.'],['Can you improve an existing site?','Yes. An inquiry can cover a focused fix, a storefront improvement, a performance review or a broader rebuild.']]); ?></div></div></section><?php cta(); ?>
<?php elseif ($page[2] === 'service'): $service=$services[$slug]; ?>
<?php pageHero('WEBOSTICS / SERVICES',$service[0],$service[1]); ?>
<section class="container page-content"><div class="content-grid mb-section"><div class="prose"><h2>The problem worth solving.</h2><p><?= e($service[2]) ?></p><h2>A practical approach.</h2><p><?= e($service[3]) ?></p><h2>What we can help with</h2><ul class="check-list"><?php foreach ($service[4] as $item): ?><li><?= e($item) ?></li><?php endforeach ?></ul><h2>How the work moves forward</h2><ol class="numbered-steps"><li><h3>Understand</h3><p>Review your goals, current setup, constraints and the people who will use the result.</p></li><li><h3>Agree the scope</h3><p>Define deliverables, responsibilities and the checks that will show the work is ready.</p></li><li><h3>Build & review</h3><p>Implement the agreed work and share it for feedback at useful checkpoints.</p></li><li><h3>Test & hand over</h3><p>Check the important journeys, document the setup and agree the next steps for launch or support.</p></li></ol></div><aside class="sidebar"><span class="eyebrow">LET’S TALK ABOUT YOUR PROJECT</span><h2>What do you need to build?</h2><p>Share the problem, your existing website if you have one, and any deadline you’re working toward.</p><a class="button primary" href="#inquiry">Discuss this service ↗</a><p class="side-note">Relevant tools and platforms</p><p><?= e($service[5]) ?></p></aside></div>
<div class="prose mb-section"><h2>Before we get started</h2><?php faq([['What should I include in my inquiry?','Share your goals, the current website or system, the main features you need and your preferred timeline. Budget guidance is helpful but optional.'],['Can this fit into an existing project?','We can discuss a focused scope for an existing site or application. Access requirements, dependencies and compatibility are reviewed before implementation.'],['What happens after launch?','Handover and support expectations are agreed with the scope. Ongoing maintenance can be discussed separately based on your setup.']]); ?></div>
<section id="inquiry" class="contact-layout"><div class="contact-aside"><span class="eyebrow">START A CONVERSATION</span><h2>Tell us about your <?= e(strtolower($service[0])) ?> project.</h2><p>We’ll use these details to understand the scope and reply to your inquiry.</p><a href="mailto:<?= e($contactEmail) ?>"><?= e($contactEmail) ?></a></div><?php require __DIR__.'/form.php'; ?></section></section>
<?php elseif ($page[2] === 'courses' || $page[2] === 'category'): $category=$page[2]==='category' ? $slug : null; ?>
<?php pageHero('WEBOSTICS LEARNING',$category ? $categories[$category].': your next step.' : 'Learn it. Build it. Make it yours.','Practical learning paths for people who want to create something. Explore the planned outlines, choose a direction, and ask about availability.'); ?>
<section class="container page-content"><div class="inline-banner"><p><strong>The course library is in development.</strong> These are planned outlines, not available lessons. Schedules, instructors, lesson counts and pricing will be shared when confirmed. You can read our free resources now.</p><a class="text-link" href="<?= e(url('resources')) ?>">Read the practical guides ↗</a><a class="standalone-link" href="<?= e(url('courses/html/first-page')) ?>">Try your first HTML lesson ↗</a></div>
<?php if (!$category): ?><div data-course-filters hidden><label class="search-label">Find a course<input type="search" data-course-search placeholder="Try JavaScript, AI, or hosting"></label><div class="filters" aria-label="Filter planned courses"><button class="filter-button" data-filter="all" aria-pressed="true">All topics</button><?php foreach ($categories as $key=>$name): ?><button class="filter-button" data-filter="<?= e($key) ?>" aria-pressed="false"><?= e($name) ?></button><?php endforeach ?></div><p class="filter-status" data-filter-status aria-live="polite"></p></div><?php endif ?>
<div class="course-grid"><?php foreach ($courses as $course) if (!$category || $course['category']===$category) courseCard($course); ?></div>
<?php if (!$category): ?><h2>Choose a learning path</h2><div class="related-links"><?php foreach ($categories as $key=>$name): ?><a href="<?= e(url('courses/'.$key)) ?>"><?= e($name) ?> ↗</a><?php endforeach ?></div><?php else: button('All learning paths','courses','outline'); endif ?></section><?php cta(); ?>
<?php elseif ($page[2] === 'course'): $course=$courses[$slug]; ?>
<?php pageHero('PLANNED COURSE / '.$course['level'],$course['title'],$course['description']); ?>
<section class="container page-content"><div class="content-grid"><div class="prose"><h2>Learn through a real project.</h2><p>This planned course connects the fundamentals to something you can build. The outline below describes the intended direction; the final curriculum will be confirmed before enrollment opens.</p><h2>What you’ll explore</h2><ul><?php foreach ($course['curriculum'] as $item): ?><li><?= e($item) ?></li><?php endforeach ?></ul><h2>Planned curriculum</h2><?php faq(array_map(fn($item)=>[$item,'Planned topic. Lesson materials and the detailed syllabus will be published when this course is ready.'],$course['curriculum'])); ?><h2>Your practice project</h2><p><?= e($course['project']) ?>. Build in small steps, explain your decisions, and check the finished result.</p><h2>Who this is for</h2><p><?= $course['level']==='Beginner' ? 'Students, freelancers, entrepreneurs and curious beginners looking for a practical starting point.' : 'Learners with some experience who want to connect their existing skills to a more complete workflow.' ?></p><h2>What you’ll need</h2><p>A computer, internet access and time to practice. Any topic-specific software or prerequisite skills will be listed in the confirmed syllabus.</p><h2>Course questions</h2><?php faq([['Can I enroll now?','Not yet. This is a planned course outline. Send a course inquiry to ask about its availability; submitting an inquiry does not enroll you or reserve a place.'],['What are the duration and price?','These details are not confirmed. We will publish the schedule, lesson count, instructor and any price before opening enrollment.'],['Are certificates included?','No certificate or accreditation is currently offered for this planned course. Any future completion features will be described explicitly.']]); ?></div><aside class="sidebar"><span class="status">Planned · Enrollment not open</span><h2>Interested in this course?</h2><p>Tell us your experience level and what you want to build. Ask about the course’s availability.</p><?php if (!empty($course['sample'])): ?><a class="button outline" href="<?= e(url($course['sample'])) ?>">Try the free HTML lesson ↗</a><p class="side-note">A complete practice activity you can use now. The full course is still planned.</p><?php endif ?><?php button('Ask about this course','contact?type=course&topic='.rawurlencode($slug)); ?><ul class="detail-list"><li>Level: <?= e($course['level']) ?></li><li>Topic: <?= e($categories[$course['category']]) ?></li><li>Schedule: To be confirmed</li><li>Instructor: To be confirmed</li><li>Pricing: To be confirmed</li></ul><a class="text-link" href="<?= e(url('courses/'.$course['category'])) ?>">More in this learning path ↗</a></aside></div></section>
<?php elseif ($page[2] === 'ai'): ?>
<?php pageHero('PRACTICAL AI','Use AI with purpose.','Understand the tools, work on a specific task, and learn to check the result. Explore AI as a practical skill for development, learning and business.'); ?>
<section class="container page-content"><div class="content-grid mb-section"><div><h2>A useful task comes first.</h2><div class="topic-grid"><?php foreach ([['For developers','Explain unfamiliar code, explore debugging ideas, draft documentation and suggest tests. Review every change before using it.'],['For students','Ask for explanations, practice questions and feedback on your reasoning. Check sources and keep doing the learning yourself.'],['For freelancers','Explore a project brief, organize research and prepare a first draft. Verify the details before sharing work with a client.'],['For businesses','Map a repetitive process and identify where drafting, categorization or summarization might help.'],['For e-commerce','Draft product content from approved specifications and review it for accuracy, consistency and tone.'],['For marketing','Explore messaging and content outlines. Check factual claims, permissions and brand requirements before publishing.'],['Prompt engineering','Give the task context, constraints and an output format. Compare results against clear acceptance criteria.'],['Automation & agents','Start with a bounded workflow, explicit permissions and a review step before any external action.']] as [$title,$description]): ?><article><h3><?= e($title) ?></h3><p><?= e($description) ?></p></article><?php endforeach ?></div></div><aside class="sidebar"><span class="eyebrow">HUMAN REVIEW, BUILT IN</span><h2>Useful doesn’t mean infallible.</h2><ul class="check-list"><li>Verify claims and generated code</li><li>Protect private and sensitive data</li><li>Review security implications</li><li>Keep approval before external actions</li></ul><?php button('Read the AI workflow guide','resources/ai','outline'); ?><p class="side-note">Need help applying AI to your business?</p><a class="text-link" href="<?= e(url('services/ai-integration')) ?>">Explore AI integration ↗</a></aside></div><?php sectionTitle('LEARN THE WORKFLOW','Planned AI learning paths.'); ?><div class="course-grid"><?php foreach (['ai-basics','prompt-engineering','ai-developers'] as $key) courseCard($courses[$key]); ?></div><a class="text-link" href="<?= e(url('courses/ai')) ?>">Explore all AI course outlines ↗</a></section><?php cta(); ?>
<?php elseif ($page[2] === 'devops'): ?>
<?php pageHero('FROM LOCALHOST TO LIVE','The build is only the beginning.','Understand how your code becomes a website people can actually use. Connect the dots between version control, servers, domains and a repeatable release.'); ?>
<section class="container page-content"><div class="content-grid mb-section"><div><h2>Your route to production.</h2><ol class="numbered-steps"><?php foreach ([['Understand the web','Start with internet basics, domains, DNS, hosting, cPanel and HTTPS. Understand which service is responsible for what.'],['Track your changes','Use Git, repositories and branches to make changes reviewable. Learn where GitHub fits into collaboration.'],['Prepare the environment','Explore Linux, VPS and cloud basics. Separate configuration from code and keep environment variables and credentials private.'],['Build a release process','Understand deployment, CI/CD and Docker fundamentals. Document what is built, what is tested and how it reaches the server.'],['Connect the domain','Point the intended domain at the production environment, preserve email records and verify HTTPS.'],['Keep it running','Plan monitoring, backups, recovery and security checks. Know how to roll back before you need to.']] as [$title,$description]): ?><li><h3><?= e($title) ?></h3><p><?= e($description) ?></p></li><?php endforeach ?></ol></div><aside class="sidebar"><span class="eyebrow">A REPEATABLE PIPELINE</span><?php foreach (['Local development','Git → GitHub','Build → checks','Server / cloud','Domain → HTTPS','Production → monitoring'] as $step): ?><div class="pipeline-step"><?= e($step) ?></div><?php endforeach ?><p class="side-note">Learning the process? Start with the launch checklist.</p><?php button('Read the launch checklist','resources/deployment','outline'); ?><a class="standalone-link" href="<?= e(url('services/hosting-deployment')) ?>">Get deployment help ↗</a></aside></div><?php sectionTitle('LEARN TO LAUNCH','Build confidence beyond the code.'); ?><div class="course-grid"><?php foreach (['git-github-basics','website-deployment','devops-basics'] as $key) courseCard($courses[$key]); ?></div></section><?php cta(); ?>
<?php elseif ($page[2] === 'resources'): ?>
<?php pageHero('THE BUILDER’S NOTEBOOK','A little clarity goes a long way.','Short, practical guides to the parts of building and launching that can feel harder than they need to. Start with the question in front of you.'); ?>
<section class="container page-content"><div class="resource-grid"><?php foreach ($resources as $key=>$resource): ?><a class="resource-card" href="<?= e(url('resources/'.$key)) ?>"><span class="eyebrow"><?= e($resource[2]) ?></span><h2><?= e($resource[0]) ?></h2><p><?= e($resource[1]) ?></p><span class="text-link">Read guide <span aria-hidden="true">↗</span></span></a><?php endforeach ?></div></section><?php cta(); ?>
<?php elseif ($page[2] === 'resource'): $resource=$resources[$slug]; ?>
<?php pageHero($resource[2],$resource[0],$resource[1]); ?>
<article class="container page-content"><div class="content-grid"><div class="prose"><?php foreach ($resource[3] as [$heading,$copy]): ?><section><h2><?= e($heading) ?></h2><p><?= e($copy) ?></p></section><?php endforeach ?><div class="inline-banner"><p>Try it on your own project: write a short checklist for the next step, then explain why each item matters.</p></div><a class="text-link" href="<?= e(url('resources')) ?>">← Back to all guides</a></div><aside class="sidebar"><span class="eyebrow">PUT IT INTO PRACTICE</span><h2>Your next step.</h2><p>Explore a related learning path or ask for help with your own project.</p><?php button('Explore learning paths','courses','outline'); ?><a class="standalone-link" href="<?= e(url('contact?type=service')) ?>">Get project help ↗</a></aside></div></article>
<?php elseif ($page[2] === 'projects'): require __DIR__.'/projects.php'; ?>
<?php elseif ($page[2] === 'about'): ?>
<?php pageHero('BUILD · LEARN · LAUNCH','Technology is better when you can use it.','Webostics brings building and learning together: practical digital services for businesses, and a growing learning direction for people who want to create things themselves.'); ?>
<section class="container page-content"><div class="content-grid"><div class="prose"><h2>One place. Two ways forward.</h2><p>If you have a business to run, you may need someone to build the website, connect the tools, or get the application online. If you want to build it yourself, you need a practical route through the technology.</p><p>Webostics is designed around both needs. Development, e-commerce, AI and deployment belong in the same conversation because that’s how real projects work.</p><h2>What guides the work</h2><ul><li>Start with the problem and the people using the result.</li><li>Choose tools that fit the scope and can be maintained.</li><li>Make learning practical with a project to work toward.</li><li>Think about testing, handover and deployment early.</li></ul><h2>A learning platform in progress.</h2><p>Our learning library is being developed. You can explore planned course outlines and read the practical resource guides now. Course availability, instructors and schedules will be announced when confirmed.</p></div><aside class="sidebar"><span class="eyebrow">START A CONVERSATION</span><h2>Meet your next project.</h2><p>Contact Saad using the existing project contact details to discuss development work or learning inquiries.</p><?php button('Contact Webostics','contact'); ?><a class="standalone-link" href="<?= e($linkedin) ?>" target="_blank" rel="noopener noreferrer">Connect with Saad on LinkedIn ↗</a></aside></div></section><?php cta(); ?>
<?php elseif ($page[2] === 'contact'): ?>
<?php pageHero('LET’S MAKE A START','What are you working on?','Tell us about a project, ask about a planned course, or start a conversation. Choose the inquiry type below so your message has the right context.'); ?>
<section class="container page-content contact-layout"><div class="contact-aside"><h2>A good conversation<br>starts with your idea.</h2><p>For projects, share what you need, your current website and any deadline. For courses, tell us what you want to learn and your experience so far.</p><a href="mailto:<?= e($contactEmail) ?>"><?= e($contactEmail) ?></a><a href="<?= e($linkedin) ?>" target="_blank" rel="noopener noreferrer">Connect with Saad on LinkedIn ↗</a><p class="notice">Courses are currently planned. A course inquiry does not enroll you, create an account or reserve a place.</p></div><?php require __DIR__.'/form.php'; ?></section>
<?php elseif ($page[2] === 'privacy'): ?>
<?php pageHero('YOUR INFORMATION','Privacy & inquiries.','A plain-language description of what happens when you contact Webostics through this website.'); ?>
<section class="container page-content prose"><h2>What the form collects</h2><p>The inquiry form asks for your name, email, inquiry type and message. You can optionally provide a phone or WhatsApp number and a budget range. Course inquiries also include your course interest and experience level.</p><h2>How your inquiry is used</h2><p>The details you submit are sent to the configured contact inbox to review and respond to your inquiry. They are not used to create an account or automatically enroll you in a course. Avoid including passwords, payment information or other sensitive material.</p><h2>Spam protection and sessions</h2><p>The form uses a session cookie to protect submissions and limit repeated requests. Google reCAPTCHA is loaded when you interact with a form to help distinguish visitors from automated submissions. Google may process device and interaction information for that purpose. See <a href="https://policies.google.com/privacy" rel="noopener noreferrer">Google’s Privacy Policy</a> and <a href="https://policies.google.com/terms" rel="noopener noreferrer">Terms of Service</a>.</p><h2>Email and hosting</h2><p>Inquiries pass through the configured email provider. The hosting environment may also retain standard access and error logs. This website does not currently provide student accounts, payments, analytics tracking or advertising integrations.</p><h2>Questions about your information</h2><p>To ask about an inquiry you sent or request deletion of your correspondence, email <a href="mailto:<?= e($contactEmail) ?>"><?= e($contactEmail) ?></a>.</p></section>
<?php else: ?>
<?php pageHero('404 / PAGE NOT FOUND','This path ends here.','The page may have moved, or the address may be incorrect. There’s still plenty to build, learn and explore.'); ?><div class="container page-content button-row"><?php button('Back to home',''); button('Explore services','services','outline'); button('Browse courses','courses','outline'); ?></div>
<?php endif ?>
