<?php pageHero('CLEAR SCOPE. A PRACTICAL START.', 'Website development plans.', 'Shopify and WordPress development starting from PKR 15,000. Choose a starting point, then get a quote based on your actual requirements.'); ?>
<div class="container page-content pricing-page">
<nav class="pricing-jumps" aria-label="Pricing sections"><a href="#shopify">Shopify plans</a><a href="#wordpress">WordPress plans</a><a href="#addons">Add-ons</a><a href="#terms">Scope & payment</a><a href="#pricing-faq">Questions</a></nav>
<div class="notice pricing-note">All prices are starting estimates in Pakistani rupees (PKR). Third-party fees are extra. Final scope, quantities and delivery dates are confirmed in your quote.</div>
<?php foreach ($pricingGroups as $platform=>$group): ?>
<section class="pricing-section" id="<?= e($platform) ?>"><?php sectionTitle('DEVELOPMENT PLANS', $group['title'], $group['intro']); ?>
<div class="pricing-grid">
<?php foreach ($pricingPlans as $key=>$plan): if ($plan['platform']!==$platform) continue; ?>
<article class="pricing-card"><span class="eyebrow"><?= e($platform==='shopify' ? 'SHOPIFY' : 'WORDPRESS / WOOCOMMERCE') ?></span><h3><?= e($plan['name']) ?></h3><p class="price-label">Starting from</p><p class="plan-price"><span>PKR</span> <?= number_format($plan['price']) ?></p><p class="plan-summary"><?= e($plan['summary']) ?></p><p class="plan-time">Estimated <?= e($plan['timeline']) ?> working days</p><ul>
<?php foreach ($group['features'] as $feature): $value=$feature[$plan['index']+1]; if ($value==='Not included' || str_starts_with($value,'Optional')) continue; ?><li><?= e($feature[0]) ?><?= $value==='Included' ? '' : ' — '.e($value) ?></li><?php endforeach ?>
</ul><p class="plan-revisions">2 revision rounds within the agreed scope</p><a class="button <?= $plan['index']===1 ? 'primary' : 'outline' ?>" href="<?= e(url('contact?type=service&topic='.$plan['topic'].'&plan='.$key)) ?>" aria-label="Request a quote for <?= e($group['title'].' '.$plan['name']) ?>">Request a quote <span aria-hidden="true">&#8599;</span></a></article>
<?php endforeach ?></div>
<details class="pricing-comparison"><summary>Compare all <?= e($platform==='shopify' ? 'Shopify' : 'WordPress / WooCommerce') ?> features</summary><div class="comparison-scroll" role="region" aria-label="<?= e($group['title']) ?> plan comparison" tabindex="0"><table><caption><?= e($group['title']) ?> — starting scope by plan</caption><thead><tr><th scope="col">Feature</th><th scope="col">Basic</th><th scope="col">Standard</th><th scope="col">Premium</th></tr></thead><tbody><?php foreach ($group['features'] as $row): ?><tr><th scope="row"><?= e($row[0]) ?></th><?php foreach (array_slice($row,1) as $value): ?><td><?= e($value) ?></td><?php endforeach ?></tr><?php endforeach ?></tbody></table></div></details>
<p class="form-help"><?= $platform==='shopify' ? 'A supplied mockup is reviewed against the chosen theme. A full bespoke design build, additional templates or complex interactions may require a higher plan or separate quote.' : 'Standard-plan WooCommerce features are optional and quoted separately. Premium includes the listed store features; product quantities and integration requirements are agreed before work begins.' ?></p>
</section><?php endforeach ?>
<section id="addons" class="pricing-section"><?php sectionTitle('EXTEND YOUR SCOPE', 'Optional add-ons.', 'Use these as a guide when planning additional work. Complexity and third-party requirements affect the final quote.'); ?><dl class="addon-grid"><?php foreach ($pricingAddons as [$label,$price]): ?><div><dt><?= e($label) ?></dt><dd>From PKR <?= e($price) ?></dd></div><?php endforeach ?></dl><p class="form-help">Add-ons apply to work outside your agreed package scope. Included features are not charged again as add-ons.</p></section>
<section id="terms" class="pricing-section"><div class="content-grid"><div class="prose"><h2>Agree the scope before the build.</h2><p>Your quote confirms page and template counts, products or variants, custom sections, integrations and the meaning of any “basic”, “limited” or “advanced” work. These plans do not include unlimited development.</p><h3>What you provide</h3><p>Final content, images, product information, required access and an approved design or reference where applicable. Estimated working days start once these materials and the requirements are ready. Content, approval and third-party delays can change the schedule.</p><h3>What is separate</h3><p>Shopify subscriptions, WordPress hosting, domains, premium themes, plugins, apps and third-party subscription or transaction fees are excluded unless explicitly included in your quote.</p><h3>Revisions and support</h3><p>Two rounds of consolidated feedback cover adjustments within the agreed design and content scope. A new design direction, extra pages, new functionality or rebuilding approved sections may add cost and time. Testing and bug fixes are included during delivery; any post-handover support period and maintenance scope are confirmed in the quote.</p></div><aside class="sidebar"><span class="eyebrow">PAYMENT TERMS</span><h2>50% to begin.<br>50% before handover.</h2><p>After the scope and quote are agreed, 50% is paid upfront to begin development. The remaining 50% is paid upon completion, before final handover.</p><p class="side-note">Requesting a quote does not place an order or collect a payment.</p><?php button('Discuss your requirements','contact?type=service'); ?></aside></div></section>
<section class="pricing-section"><?php sectionTitle('FROM BRIEF TO LAUNCH', 'How the work moves forward.'); ?><ol class="numbered-steps"><li><h3>Requirements</h3><p>Review the brief, content, references and access. Agree the scope and quote.</p></li><li><h3>Development</h3><p>Implement the approved design or reference on Shopify or WordPress.</p></li><li><h3>Review</h3><p>Review the build and send consolidated feedback.</p></li><li><h3>Revisions</h3><p>Complete the two included revision rounds within scope.</p></li><li><h3>Testing & launch</h3><p>Check responsive layouts and functionality, then arrange deployment and handover.</p></li></ol></section>
<section id="pricing-faq" class="pricing-section"><h2>Questions before you choose?</h2><?php faq([
['Are these fixed prices?','No. They are starting estimates in PKR. Your final quote depends on the complete requirements, quantities and integrations.'],
['Is the timeline guaranteed?','Timelines are estimates in working days, starting once all required materials, access and requirements are ready. The final delivery plan is confirmed after reviewing the scope.'],
['Are hosting, subscriptions and paid plugins included?','No, unless your quote explicitly includes them. Domains, hosting, Shopify subscriptions, paid themes, plugins, apps and third-party fees are separate.'],
['Can I request a custom design in Basic Shopify?','Send the design first. Basic pricing assumes implementation fits the agreed theme scope. Bespoke layouts or additional custom sections may need another plan or a separate quote.'],
['Does maintenance cover unlimited changes?','No. Monthly maintenance starts at PKR 5,000 per month. Tasks, limits, response expectations and any bug-fix support period are agreed separately.'],
['What about mobile apps, Magento or BigCommerce?','These projects need a custom quote. Share the workflows, platform, integrations and requirements so we can define a suitable scope.']
]); ?></section>
<section class="inline-banner"><h2>A different kind of build?</h2><p>Mobile apps, Magento 2, BigCommerce and custom web applications are quoted individually.</p><div class="related-links"><?php foreach (['mobile-app-development','magento-2','bigcommerce','web-applications'] as $serviceKey): ?><a href="<?= e(url('services/'.$serviceKey)) ?>"><?= e($services[$serviceKey][0]) ?> &#8599;</a><?php endforeach ?></div><?php button('Request a custom quote','contact?type=service'); ?></section>
</div>
